CREATE TABLE Users 
      (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL UNIQUE,
        username VARCHAR(255) UNIQUE,
        email VARCHAR(255) UNIQUE,
        createdAT timestamp NOT NULL DEFAULT now(),
        PRIMARY KEY (id)
      )
