CREATE TABLE Posts 
      (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
        src_id VARCHAR(100),
        body VARCHAR(9999),
        username VARCHAR(100) references Users(username),
        createdAT timestamp NOT NULL DEFAULT now(),
        PRIMARY KEY (id)
      );