CREATE TABLE PostLikes 
      (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
        PostID VARCHAR(255) NOT NULL references Posts(src_id),
        username VARCHAR(255),
        createdAT timestamp NOT NULL DEFAULT now()
      );