CREATE TABLE PostLikes 
      (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
        PostID INT NOT NULL references Posts(id),
        username VARCHAR(255),
        userID INT NOT NULL references Users(id)
      );