CREATE TABLE PostComments 
      (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
        PostID INT NOT NULL references Posts(id),
        body VARCHAR(1000),
        UserName VARCHAR(100) references Users(username),
        createdAT timestamp NOT NULL DEFAULT now()
      );